[package]
name = "apt_casino_plinko"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/movement-core.git", subdir = "movement-move/framework/movement-framework/", rev = "main" }

[addresses]
apt_casino = "_"


