[package]
name = "movement_casino"
version = "1.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/movement-core.git", subdir = "movement-move/framework/movement-framework/", rev = "movement-node-v1.8.0" }

[addresses]
movement_casino = "_"